### PR TITLE
Change sidebar link to reference `jasper-helpers.md`

### PR DESCRIPTION
**Pull request by marksiemers**

### CODE REVIEW

**Comment by marksiemers** [comment]
The changes from https://github.com/amberframework/online-docs/pull/28 are not showing up on the `/guides` site because the sidebar has been referencing `jasper-helpers.html` rather than `.md`

**Comment by marksiemers** [comment]
I also noticed that the indentation of slim/slang doesn't quite display correctly (at least in my version of chrome). It isn't unique to the `jasper-helpers.md` page.

It also exists here: https://amberframework.org/guides#getting-started/views/README.md
(right under "An example views/home/index.slang:")

**Comment by faustinoaq** [comment]
Hi @marksiemers I already did these changes on #51 , please check https://amberframework-pr-51.herokuapp.com/guides/ 😄

**Comment by marksiemers** [comment]
Nice, the formatting of slim/slang looks way better too!

**Pull request closed without merging**
