### PR TITLE
Refactoring Blog management and fixes Heroku deploy

### PR DESCRIPTION
**Pull request by faustinoaq**
Outdated shard.lock. Please run shards update instead.

I fixed it using amberframework `0.3.0` instead of master

Also opened a PR here 👉  https://github.com/crystal-community/icr/pull/69

## Update (2017-10-28)

Refactor & simplify blog management, highly inspired by [kamber](https://github.com/f/kamber)

- Moves posts metadata to `posts.yml`
- Add date to post url
- Organize posts using subdirectories
- Small padding changes

With these changes on blog management is easier to post something following these steps:

Current blog structure:

```
blog
├── 2017
│   └── 10
│       ├── 07
│          └── new-website-for-amber-framework.md
└── posts.yml
```

1. Create a sub-folder using the pattern `year/month/day`
2. Create a markdown file with post content
3. Update `blog/posts.yml` with your post metadata (add to beginning)

```
title: post title
file: blog/year/month/day/filename.md
date: Month (abbreviation) day (number), Year
author: Full Name
profile: Internet Profile URL
---
title: New website for Amber Framework
file: blog/2017/10/07/new-website-for-amber-framework.md
date: Oct 07, 2017
author: Faustino Aguilar
profile: https://github.com/faustinoaq
```

### CODE REVIEW

**Comment by faustinoaq** [comment]
@eliasjpr I think this PR is ready to merge 😅

**Comment by faustinoaq** [comment]
@amberframework/core-team I did some enhancements in blog management, using a YAML file, review here 👉 https://amberframework-pr-55.herokuapp.com/blog

**Comment by faustinoaq** [comment]
@veelenga WDYT about this blog approach ? Also I think we can write something in medium like @eliasjpr  suggested.

**Comment by eliasjpr** [comment]
This is awesome! 

TheSaas theme has a nice blog layout now that the posts are organized in a YAML i think we can layout like this http://preview.themeforest.net/item/thesaas-responsive-bootstrap-saas-software-webapp-template/full_screen_preview/19778599

**Comment by faustinoaq** [comment]
@eliasjpr Yeah, We can use a new layout for blog based on TheSaas, I will open a new PR implementing the new design, after this PR is merged 👍

**Pull request merged**
