### PR TITLE
Upgrade: amber v0.6.1, crystal v0.24.1, amber_spec => garnet_spec

### PR DESCRIPTION
**Pull request by marksiemers**

### CODE REVIEW

**Comment by marksiemers** [comment]
This is a less aggressive upgrade approach. @amberframework/core-team WDYT?

**Comment by marksiemers** [comment]
Well shoot, the pr deployment didn't work. I'm gonna leave this for the day - if anyone has suggestions feel free to add commits / modify the PR.

**Comment by eliasjpr** [comment]
I made some changes to this PR to fix the heroku preview. I also improved the amber heroku buildpack to cache the `amber cli` so it only builds the cli on the first deployment.

**Comment by eliasjpr** [comment]
@elorest I can run this branch locally with no issues. I think one of the reason that it does not have the environment yamls is because at the time we create the site amber did not support yaml

**Comment by marksiemers** [comment]
@elorest and @eliasjpr - So this PR and #92 should be considered alternatives to each other. Only one should be merged. Just want to clarify that.

The other PR has the yaml files and encrypted production file.

The other one should work, as long as the `encryption_key` is provided as an environment variable on any "production" machine that this will be deployed to. Does that seem like a reasonable thing to accomplish?

**Comment by marksiemers** [comment]
Well, this one is working and #92 is not.

@elorest and @eliasjpr - Should we just merge this and drop the other one?

**Comment by marksiemers** [comment]
#92 Took care of this.

**Pull request closed without merging**
