### PR TITLE
Fix overflown sidebar in guides (for mobile)

### PR DESCRIPTION
**Pull request by mtking2**
The bottom of the sidebar in guides route tends to overflow a bit, especially when viewing from a mobile device. This minor CSS tweak should resolve that.

### CODE REVIEW

**Comment by faustinoaq** [comment]
Hi @mtking2 I already fixed it on #35 , please take a look 😄

**Comment by faustinoaq** [comment]
@eliasjpr I already did these changes on #35 , If you want we can merge this PR before

**Comment by faustinoaq** [comment]
Thanks you @mtking2 for collaborate on Amber Framework! 😄

**Comment by faustinoaq** [comment]
@eliasjpr Is this PR still needed? Maybe @mtking2 could check the new website update and tell us if the issue is still there 😅

**Comment by mtking2** [comment]
@faustinoaq Your changes in #35 seems to have cleared up the issue for the most part. I merged in master just in case. 

When scrolling in the guides side bar, the scroll bar still appears to overflow just a tiny bit when you get to the very bottom. The few changes in this PR make the element an exact fit. The main issue was some of last items in the list were unaccessible due to the overflow. #35 did fix that though. But if want to take a look at it, then let me know if this is still worth merging. I realize it's very minor at this point.

**Comment by faustinoaq** [comment]
Yeah, Now I understand 😅 I think this PR improves accessibility!

@mtking2 Thanks you for your collaboration again!

@eliasjpr I think this PR is ready to merge

**Pull request merged**
