### PR TITLE
Adds error handling when serving static content

### PR DESCRIPTION
**Pull request by eliasjpr**

### CODE REVIEW

**Comment by drujensen** [comment]
@eliasjpr should we add this type of plugin to our templates as well?

**Comment by drujensen** [comment]
also, do we need the 404 as well? https://github.com/amberframework/amberframework.org/blob/master/src/controllers/error_controller.cr#L2

**Comment by eliasjpr** [comment]
We have an error handler in the amber core framework. My understanding that this one is a custom one built for the amberframework.org site @faustinoaq maybe he can shed some light.

**Comment by faustinoaq** [comment]
@eliasjpr yeah I'm using a custom error handler. However I think we can implement something more professional but for now this works :sweat_smile:

I also did a hack here : https://github.com/amberframework/amberframework.org/blob/master/src/controllers/static_controller.cr#L3

**Pull request merged**
